#!/usr/bin/env node
import fs from 'fs'
import path from 'path'
import readline from 'readline'

const cwd = process.cwd()
const args = process.argv.slice(2)
const command = args[0]

// ─── Init ────────────────────────────────────────────────────────────────────

const PLUGIN_DEST = 'plugins/css-icons.ts'
const CONFIG_DEST = 'css-icons.config.mjs'

const PLUGIN_CONTENT = `import { defineNuxtPlugin } from '#app'
import { defineComponent, h, type PropType } from 'vue'
import BaseIcon from '@itsogden/css-icons/component'
// @ts-ignore — generated by \`pnpm css-icons\`
import { getIconClass, type CssIconName } from './css-icons/icons'

const CssIcon = defineComponent({
  name: 'CssIcon',
  props: {
    icon: {
      type: String as PropType<CssIconName>,
      required: true,
    },
    useWidth: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    return () => h(BaseIcon, {
      className: \`\${getIconClass(props.icon)}\${props.useWidth ? ' scale-width' : ''}\`,
    })
  },
})

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('CssIcon', CssIcon)
})
`

const CONFIG_CONTENT = `export default {
  // Where your SVG files live
  iconFolder: './assets/icons',

  // SVGs inside this folder won't have the folder name appended to their icon name.
  // e.g. duotone/gear.svg becomes 'duotone-gear' not 'duotone-gear-duotone'
  defaultFolder: 'duotone',

  // Where to write the generated css-icon.css and icons.ts files.
  // This folder should be committed to your repo.
  outDir: './plugins/css-icons',

  // Optional: folders whose icons use background-image instead of mask (for full-color SVGs)
  // backgroundFolders: ['colored'],
}
`

function prompt(rl, question) {
    return new Promise((resolve) => rl.question(question, resolve))
}

function checkMark() { return '\x1b[32m✔\x1b[0m' }
function warn() { return '\x1b[33m!\x1b[0m' }
function info() { return '\x1b[36mℹ\x1b[0m' }

async function init() {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
    console.log('\n\x1b[1m@itsogden/css-icons setup\x1b[0m\n')

    // ── Config file ─────────────────────────────────────────────────────────────
    const configPath = path.join(cwd, CONFIG_DEST)
    if (fs.existsSync(configPath)) {
        console.log(`${checkMark()} ${CONFIG_DEST} already exists, skipping.`)
    } else {
        const ans = await prompt(rl, `${info()} Create ${CONFIG_DEST}? (Y/n): `)
        if (ans.trim().toLowerCase() !== 'n') {
            const iconFolder = await prompt(rl, `${info()} Icon folder path (default: ./assets/icons): `)
            const defaultFolder = await prompt(rl, `${info()} Default folder name, omitted from icon names (default: duotone): `)
            const outDir = await prompt(rl, `${info()} Output directory for generated files (default: ./plugins/css-icons): `)

            const configContent = `export default {
  // Where your SVG files live
  iconFolder: '${iconFolder.trim() || './assets/icons'}',

  // SVGs inside this folder won't have the folder name appended to their icon name.
  // e.g. duotone/gear.svg becomes 'duotone-gear' not 'duotone-gear-duotone'
  defaultFolder: '${defaultFolder.trim() || 'duotone'}',

  // Where to write the generated css-icon.css and icons.ts files.
  // This folder should be committed to your repo.
  outDir: '${outDir.trim() || './plugins/css-icons'}',

  // Optional: folders whose icons use background-image instead of mask (for full-color SVGs)
  // backgroundFolders: ['colored'],
}
`
            fs.writeFileSync(configPath, configContent, 'utf8')
            console.log(`${checkMark()} Created ${CONFIG_DEST}`)
        } else {
            console.log(`${warn()} Skipped ${CONFIG_DEST} — you'll need to create it manually.`)
        }
    }

    // ── Plugin file ──────────────────────────────────────────────────────────────
    const pluginPath = path.join(cwd, PLUGIN_DEST)
    if (fs.existsSync(pluginPath)) {
        console.log(`${checkMark()} ${PLUGIN_DEST} already exists, skipping.`)
    } else {
        const ans = await prompt(rl, `${info()} Create ${PLUGIN_DEST}? (Y/n): `)
        if (ans.trim().toLowerCase() !== 'n') {
            fs.mkdirSync(path.dirname(pluginPath), { recursive: true })
            fs.writeFileSync(pluginPath, PLUGIN_CONTENT, 'utf8')
            console.log(`${checkMark()} Created ${PLUGIN_DEST}`)
        } else {
            console.log(`${warn()} Skipped ${PLUGIN_DEST} — you'll need to create it manually.`)
        }
    }

    // ── package.json scripts ─────────────────────────────────────────────────────
    const pkgPath = path.join(cwd, 'package.json')
    if (fs.existsSync(pkgPath)) {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
        pkg.scripts = pkg.scripts || {}
        let changed = false

        if (pkg.scripts['css-icons']) {
            console.log(`${checkMark()} package.json "css-icons" script already exists, skipping.`)
        } else {
            const ans = await prompt(rl, `${info()} Add "css-icons" script to package.json? (Y/n): `)
            if (ans.trim().toLowerCase() !== 'n') {
                pkg.scripts['css-icons'] = 'node ./node_modules/@itsogden/css-icons/index.mjs'
                changed = true
                console.log(`${checkMark()} Added "css-icons" script`)
            }
        }

        if (pkg.scripts['dev']?.includes('css-icons')) {
            console.log(`${checkMark()} package.json "dev" script already includes css-icons, skipping.`)
        } else if (!pkg.scripts['dev']) {
            console.log(`${warn()} No "dev" script found in package.json, skipping.`)
        } else {
            const ans = await prompt(rl, `${info()} Patch "dev" script to run css-icons in watch mode alongside nuxt? (Y/n): `)
            if (ans.trim().toLowerCase() !== 'n') {
                if (process.platform === 'win32') {
                    pkg.scripts['dev'] = `concurrently "pnpm css-icons --watch" "${pkg.scripts['dev']}"`
                    pkg.devDependencies = pkg.devDependencies || {}
                    pkg.devDependencies['concurrently'] = 'latest'
                    changed = true
                    console.log(`${checkMark()} Patched "dev" script (Windows — using concurrently)`)
                    console.log(`${warn()} Run pnpm install to complete concurrently installation`)
                } else {
                    pkg.scripts['dev'] = `pnpm css-icons --watch & ${pkg.scripts['dev']}`
                }
                changed = true
                console.log(`${checkMark()} Patched "dev" script`)
            }
        }

        if (pkg.scripts['build']?.includes('css-icons')) {
            console.log(`${checkMark()} package.json "build" script already includes css-icons, skipping.`)
        } else if (!pkg.scripts['build']) {
            console.log(`${warn()} No "build" script found in package.json, skipping.`)
        } else {
            const ans = await prompt(rl, `${info()} Patch "build" script to generate icons before nuxt build? (Y/n): `)
            if (ans.trim().toLowerCase() !== 'n') {
                pkg.scripts['build'] = `pnpm css-icons && ${pkg.scripts['build']}`
                changed = true
                console.log(`${checkMark()} Patched "build" script`)
            }
        }

        if (changed) {
            fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8')
        }
    } else {
        console.log(`${warn()} No package.json found, skipping script setup.`)
    }

    // ── nuxt.config.ts reminder ──────────────────────────────────────────────────
    console.log(`
${warn()} One manual step required — add the generated CSS to your nuxt.config.ts:

  \x1b[36mcss: ['~/plugins/css-icons/css-icon.css']\x1b[0m

`)

    rl.close()

    // ── Initial build ────────────────────────────────────────────────────────────
    if (fs.existsSync(path.join(cwd, CONFIG_DEST))) {
        const ans2 = await new Promise((resolve) => {
            const rl2 = readline.createInterface({ input: process.stdin, output: process.stdout })
            rl2.question(`${info()} Run initial icon build now? (Y/n): `, (a) => { rl2.close(); resolve(a) })
        })
        if (ans2.trim().toLowerCase() !== 'n') {
            console.log('\n[css-icons] running initial build...')
            await build()
        }
    }

    console.log(`\n\x1b[1mDone!\x1b[0m Run \x1b[36mpnpm css-icons\x1b[0m to regenerate at any time.\n`)
}

// ─── Build / Watch ────────────────────────────────────────────────────────────

async function loadConfig() {
    const candidates = ['css-icons.config.mjs', 'css-icons.config.js']
    for (const file of candidates) {
        const full = path.join(cwd, file)
        if (fs.existsSync(full)) {
            const mod = await import(pathToFileUrl(full))
            return mod.default || mod
        }
    }
    throw new Error('Could not find css-icons.config.mjs — run `pnpm css-icons init` first')
}

function pathToFileUrl(filePath) {
    let resolved = path.resolve(filePath).replace(/\\/g, '/')
    if (!resolved.startsWith('/')) resolved = '/' + resolved
    return 'file://' + resolved
}

function toPosix(p) { return p.replace(/\\/g, '/') }

function walkSvgFiles(dir, baseDir = dir, out = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
        const full = path.join(dir, entry.name)
        if (entry.isDirectory()) walkSvgFiles(full, baseDir, out)
        else if (entry.isFile() && entry.name.toLowerCase().endsWith('.svg'))
            out.push(toPosix(path.relative(baseDir, full)))
    }
    return out
}

function svgToDataUri(svg) {
    return 'data:image/svg+xml,' + encodeURIComponent(svg.replace(/\r?\n|\r/g, ' ').trim())
}

function buildIconRecord(relPath, config) {
    const clean = toPosix(relPath)
    const noExt = clean.replace(/\.svg$/i, '')
    const parts = noExt.split('/').filter(Boolean)
    const fileName = parts.pop()
    const folder = parts[parts.length - 1] || ''
    const stem = fileName
    const isDefault = !!config.defaultFolder && folder === config.defaultFolder
    const icon = isDefault ? stem : (folder ? `${stem}-${folder}` : stem)
    const isBackground = (config.backgroundFolders || []).includes(folder)
    const implClass = folder ? `i-${stem}-${folder}` : `i-${stem}`
    const baseClass = stem
    return { relPath: clean, folder, stem, icon, baseClass, implClass, isBackground }
}

function generateCss(icons, config) {
    const iconFolder = path.resolve(cwd, config.iconFolder)
    let css = ''
    css += `.icon { display: inline-block; vertical-align: middle; line-height: 1; }\n`
    css += `.icon::after { content: ""; display: inline-block; height: 1em; width: 1em; background-color: currentColor; mask-size: contain; mask-repeat: no-repeat; mask-position: center; -webkit-mask-size: contain; -webkit-mask-repeat: no-repeat; -webkit-mask-position: center; }\n`
    css += `.icon.scale-width::after { width: var(--icon-width, 1em); }\n`
    css += `.icon.colored::after { background-color: transparent; background-size: contain; background-repeat: no-repeat; background-position: center; }\n\n`
    css += `:root {\n`
    for (const icon of icons) {
        const svgPath = path.join(iconFolder, icon.relPath)
        const svg = fs.readFileSync(svgPath, 'utf8')
        css += `  --${icon.implClass}: url("${svgToDataUri(svg)}");\n`
    }
    css += `}\n\n`
    for (const icon of icons) {
        css += `.${icon.implClass}::after {\n`
        css += `  --icon-width: 1em;\n`
        if (icon.isBackground) {
            css += `  background-image: var(--${icon.implClass});\n`
        } else {
            css += `  mask-image: var(--${icon.implClass});\n`
            css += `  -webkit-mask-image: var(--${icon.implClass});\n`
        }
        css += `}\n\n`
    }
    return css
}

function generateTypes(icons) {
    const typeNames = icons.map((icon) => `  | '${icon.icon}'`).join('\n') || `  | 'error'`
    const entries = icons.map((icon) => {
        const className = `${icon.baseClass} ${icon.implClass}${icon.isBackground ? ' colored' : ''}`
        return `  '${icon.icon}': { icon: '${icon.icon}', folder: '${icon.folder}', className: '${className}' }`
    }).join(',\n')
    return `export type CssIconName =\n${typeNames}\n\nexport const cssIconMap = {\n${entries}\n} as const\n\nexport function getIconClass(name: CssIconName): string {\n  return cssIconMap[name].className\n}\n`
}

function writeFiles(config, css, types, count) {
    const outDir = path.resolve(cwd, config.outDir || './plugins/css-icons')
    fs.mkdirSync(outDir, { recursive: true })
    fs.writeFileSync(path.join(outDir, 'css-icon.css'), css, 'utf8')
    fs.writeFileSync(path.join(outDir, 'icons.ts'), types, 'utf8')
    console.log(`[css-icons] generated ${count} icons → ${outDir}`)
    return outDir
}

async function build() {
    const config = await loadConfig()
    const iconDir = path.resolve(cwd, config.iconFolder)
    if (!fs.existsSync(iconDir)) throw new Error(`iconFolder does not exist: ${iconDir}`)
    const files = walkSvgFiles(iconDir)
    const icons = files.map((f) => buildIconRecord(f, config)).sort((a, b) => a.icon.localeCompare(b.icon))
    const css = generateCss(icons, config)
    const types = generateTypes(icons)
    writeFiles(config, css, types, icons.length)
}

async function watch() {
    const config = await loadConfig()
    const iconDir = path.resolve(cwd, config.iconFolder)
    let timer = null
    const rerun = () => {
        clearTimeout(timer)
        timer = setTimeout(() => build().catch(console.error), 300)
    }
    await build()
    fs.watch(iconDir, { recursive: true }, (eventType, filename) => {
        if (!filename?.toLowerCase().endsWith('.svg')) return
        rerun()
    })
    console.log('[css-icons] watching for svg changes...')
}

// ─── Entry ────────────────────────────────────────────────────────────────────

if (command === 'init') {
    init().catch((err) => { console.error(err); process.exit(1) })
} else if (command === '--watch') {
    watch().catch((err) => { console.error(err); process.exit(1) })
} else {
    build().catch((err) => { console.error(err); process.exit(1) })
}